export const commonLanguages = {
  en: 'English',
  'en-US': 'English (US)',
  'en-AU': 'English (AU)',
  'en-GB': 'English (GB)',
  'en-NZ': 'English (NZ)',
  // 'en-IN': 'English (India)',
  bg: 'Bulgarian',
  ca: 'Catalan',
  cs: 'Czech',
  da: 'Danish',
  // 'da-DK': 'Danish',
  nl: 'Dutch',
  et: 'Estonian',
  fi: 'Finnish',
  // 'nl-BE': 'Flemish',
  fr: 'French',
  'fr-CA': 'French (Canada)',
  de: 'German',
  'de-CH': 'German (Switzerland)',
  el: 'Greek',
  hi: 'Hindi',
  // 'hi-Latn': 'Hindi',
  hu: 'Hungarian',
  id: 'Indonesian',
  it: 'Italian',
  ja: 'Japanese',
  ko: 'Korean',
  // 'ko-KR': 'Korean',
  lv: 'Latvian',
  lt: 'Lithuanian',
  ms: 'Malay',
  no: 'Norwegian',
  pl: 'Polish',
  pt: 'Portuguese',
  'pt-BR': 'Portuguese (Brazil)',
  ro: 'Romanian',
  ru: 'Russian',
  sk: 'Slovak',
  es: 'Spanish',
  'es-419': 'Spanish (Latin America)',
  sv: 'Swedish',
  // 'sv-SE': 'Swedish (Sweden)',
  th: 'Thai',
  // 'th-TH': 'Thai (Thailand)',
  tr: 'Turkish',
  uk: 'Ukrainian',
  vi: 'Vietnamese',
  zh: 'Chinese (Mandarin, Simplified)',
  // 'zh-CN': 'Chinese (Mandarin, Simplified)',
  // 'zh-Hans': 'Chinese (Mandarin, Simplified)',
  'zh-TW': 'Chinese (Mandarin, Traditional)',
  // 'zh-Hant': 'Chinese (Mandarin, Traditional)',
  'zh-HK': 'Chinese (Cantonese, Traditional)',
};

export const inputOnlyLanguages = {
  multi: 'English & Spanish (Bilingual)',
};

export const inputLanguages = {
  ...commonLanguages,
  ...inputOnlyLanguages,
};

export type InputLanguage = keyof typeof inputLanguages;

export const outputOnlyLanguages = {
  af: 'Afrikaans',
  ar: 'Arabic',
  am: 'Amharic',
  bn: 'Bengali',
  cy:	'Welsh',
  fa: 'Farsi/Persian',
  gu:	'Gujarati',
  he: 'Hebrew',
  hmn: 'Hmong',
  hr: 'Croatian',
  ht: 'Haitian Creole',
  hy: 'Armenian',
  is:	'Icelandic',
  jv:	'Javanese',
  ka: 'Georgian',
  km: 'Khmer',
  kn:	'Kannada',
  ln:	'Lingala',
  mh: 'Marshallese',
  ml:	'Malayalam',
  mr:	'Marathi',
  my:	'Burmese',
  ne:	'Nepali',
  pa:	'Punjabi',
  rw: 'Kinyarwanda',
  sr: 'Serbian',
  si:	'Sinhala',
  sl:	'Slovene',
  sm: 'Samoan',
  so: 'Somali',
  su:	'Sundanese',
  sw: 'Swahili',
  ta:	'Tamil',
  te:	'Telugu',
  tl: 'Tagalog',
  ur: 'Urdu',
  zu: 'Zulu',
};

export const outputLanguages = {
  ...commonLanguages,
  ...outputOnlyLanguages,
};

export type OutputLanguage = keyof typeof outputLanguages;

export const isRtl = new Set(['ar', 'fa', 'he']);
