export const commonLanguages = {
  ar: 'Arabic',
  ba: 'Bashkir',
  eu: 'Basque',
  be: 'Belarusian',
  bn: 'Bengali',
  bg: 'Bulgarian',
  // 'yue': 'Cantonese',
  ca: 'Catalan',
  zh: 'Chinese (Mandarin, Simplified)',
  // 'zh-CN': 'Chinese (Mandarin, Simplified)',
  // 'zh-Hans': 'Chinese (Mandarin, Simplified)',
  'zh-TW': 'Chinese (Mandarin, Traditional)',
  // 'zh-Hant': 'Chinese (Mandarin, Traditional)',
  'zh-HK': 'Chinese (Cantonese, Traditional)',
  hr: 'Croatian',
  cs: 'Czech',
  da: 'Danish',
  nl: 'Dutch',
  en: 'English',
  'en-US': 'English (US)',
  'en-AU': 'English (AU)',
  'en-GB': 'English (GB)',
  'en-NZ': 'English (NZ)',
  eo: 'Esperanto',
  et: 'Estonian',
  fi: 'Finnish',
  fr: 'French',
  'fr-CA': 'French (Canada)',
  gl: 'Galician',
  de: 'German',
  'de-CH': 'German (Switzerland)',
  el: 'Greek',
  he: 'Hebrew',
  hi: 'Hindi',
  hu: 'Hungarian',
  id: 'Indonesian',
  // 'ia': 'Interlingua',
  ga: 'Irish',
  it: 'Italian',
  ja: 'Japanese',
  ko: 'Korean',
  lv: 'Latvian',
  lt: 'Lithuanian',
  ms: 'Malay',
  // 'en_ms': 'Malay & English bilingual',
  mt: 'Maltese',
  // 'cmn': 'Mandarin',
  // 'cmn_en': 'Mandarin & English bilingual',
  // 'cmn_en_ms_ta': 'Mandarin Malay Tamil & English multilingual',
  mr: 'Marathi',
  mn: 'Mongolian',
  no: 'Norwegian',
  fa: 'Persian (Farsi)',
  pl: 'Polish',
  pt: 'Portuguese',
  'pt-BR': 'Portuguese (Brazil)',
  ro: 'Romanian',
  ru: 'Russian',
  sk: 'Slovakian',
  sl: 'Slovenian',
  es: 'Spanish',
  'es-419': 'Spanish (Latin America)',
  multi: 'Spanish & English (Bilingual)',
  sw: 'Swahili',
  sv: 'Swedish',
  tl: 'Tagalog (Filipino)',
  ta: 'Tamil',
  // 'en_ta': 'Tamil & English bilingual',
  th: 'Thai',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  ug: 'Uyghur',
  vi: 'Vietnamese',
  cy: 'Welsh',
};

export const inputOnlyLanguages = {
  multi: 'English & Spanish (Bilingual)',
};

export const inputLanguages = {
  ...commonLanguages,
  ...inputOnlyLanguages,
};

export type InputLanguage = keyof typeof inputLanguages;

export const outputOnlyLanguages = {
  af: 'Afrikaans',
  // ar: 'Arabic',
  am: 'Amharic',
  // bn: 'Bengali',
  // cy: 'Welsh',
  // fa: 'Persian',
  gu: 'Gujarati',
  // he: 'Hebrew',
  hmn: 'Hmong',
  // hr: 'Croatian',
  ht: 'Haitian Creole',
  hy: 'Armenian',
  is: 'Icelandic',
  jv: 'Javanese',
  ka: 'Georgian',
  km: 'Khmer',
  kn: 'Kannada',
  ln: 'Lingala',
  mh: 'Marshallese',
  ml: 'Malayalam',
  // mr: 'Marathi',
  my: 'Burmese',
  ne: 'Nepali',
  pa: 'Punjabi',
  rw: 'Kinyarwanda',
  sr: 'Serbian',
  si: 'Sinhala',
  // sl: 'Slovene',
  sm: 'Samoan',
  so: 'Somali',
  su: 'Sundanese',
  // sw: 'Swahili',
  // ta: 'Tamil',
  te: 'Telugu',
  // tl: 'Tagalog',
  // ur: 'Urdu',
  zu: 'Zulu',
};

export const outputLanguages = {
  ...commonLanguages,
  ...outputOnlyLanguages,
};

export type OutputLanguage = keyof typeof outputLanguages;

export const isRtl = new Set(['ar', 'fa', 'he']);
